### ISSUE TITLE
Doesn't seem to be working. Debug gives SyntaxError

### ISSUE THREAD

**Issue by jdziekonski** [Hurray0/uebersicht-live2d#1]
Doesn't seem to be working on Big Sur 11.6.3
Ubersicht debug gives SyntaxError in waifu-tips.js, live2d.js, run.js.lib

**Comment by Hurray0** [comment]
I am working on Big Sur 11.5.2 and it works fine.
My ubersicht version is 1.6. I wonder if it is not the problem of system but ubersicht app.

**Comment by jdziekonski** [comment]
I'm also on 1.6. Maybe it's something on my side then, or system locale difference.

**Comment by Hurray0** [comment]
I just update the OS version to 12.2.1 and it works.

**Comment by Hurray0** [comment]
It is modified by a public js file, and I also put it on my blog [https://www.hurray0.com](https://www.hurray0.com)
You can debug it yourself for try.

**Comment by jdziekonski** [comment]
Sure, I'll try in my spare time. I'll close the issue, if anyone has problems feel free to reopen it.

**Comment by Hurray0** [comment]
sorry, I notice the problem.
You can rename the widget folder name from waifu.widget to waifu, and it will work.

**Comment by Hurray0** [comment]
Currently, the file `waifu.widget.zip` is able to use.

**Comment by Hurray0** [comment]
Currently, the file waifu.widget.zip is able to use.
New users don't need to change the folder name.
