### ISSUE TITLE
How do I get it working?

### ISSUE THREAD

**Issue by alexngyn** [Hurray0/uebersicht-live2d#3]
I've simply put it into the widgets folder and it does not show up on my desktop. I have already tried renaming it from waifu.widget to waifu.

**Comment by Hurray0** [comment]
You can open the debug window to see the debug information.
Currently, you can use `waifu.widget` for `waifu.widget.zip` file.

**Comment by Hurray0** [comment]
If there still exists problems, please show me the detailed debug infomation in `übersicht`.
Otherwise, the issue will be closed in some day.

**Comment by flooof** [comment]
![Screen Shot 2022-08-15 at 16 34 51](https://user-images.githubusercontent.com/93253390/184612309-59f11f09-8d2c-463f-86aa-2aeda643aed3.png)
This is the debug console, if I check those files in the sources tab I see
![Screen Shot 2022-08-15 at 16 36 16](https://user-images.githubusercontent.com/93253390/184612520-f8f265db-3057-4945-b93a-b9aad109bfde.png)
which I believe is wrong. The code inside waifu.widget/lib/live2d.js is filled with javascript thou.

**Comment by alexngyn** [comment]
Here is some debug information
![Screen Shot 2022-08-15 at 16 47 45](https://user-images.githubusercontent.com/93253390/184614143-9cb0a4ca-e2d9-44fd-95ee-13974ccc5de3.png)
![Screen Shot 2022-08-15 at 16 48 02](https://user-images.githubusercontent.com/93253390/184614180-14c7a486-ec67-434d-b00e-afabcc954768.png)

**Comment by Hurray0** [comment]
Sorry to offer a bad experience.
There was a bug in `lib/run.js.lib` which gives a wrong URL of modle.
I already update the new version file and handled above bug. Please download again and have a nice day!

Thank you for your debug feedback! Please tell me the new result and that helps the project a lot.

**Comment by alexngyn** [comment]
Yes, now it works.
